---
- hosts: greco_ec2
  name: configuration play
  user: ec2-user

  gather_facts: false
  

  tasks:

    - name: yum update all
      register: yumout
      become: true
      yum:
        name: '*'
        state: latest

    - name: Allow 'wheel' group to have passwordless sudo
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: create users
      become: true
      user:
        name: tgrecojr
        groups: wheel
        append: yes

    - name: add authorized keye
      become: true
      authorized_key:
        user: tgrecojr
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: remove user
      become: true
      user:
        name: ec2-user
        state: absent
        remove: yes
        force: true
  
